# Pandas DataFrame Oluşturma

In [1]:
import pandas as pd

In [2]:
l = [22, 33, 44, 55, 66]
l

[22, 33, 44, 55, 66]

In [3]:
pd.DataFrame(l)

0
0  22
1  33
2  44
3  55
4  66

In [4]:
pd.DataFrame(l, columns=["degisken_ismi"])

degisken_ismi
0             22
1             33
2             44
3             55
4             66

In [5]:
import numpy as np

In [6]:
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
pd.DataFrame(m, columns=["var1", "var2", "var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

# DataFrame İsimlendirme

In [8]:
df = pd.DataFrame(m, columns=["var1","var2","var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [9]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [10]:
#my_dictionary = {"index1":"murat",
#                "index2":"havvanur",
#                "index3":"eva"}
#my_dataFrame = pd.DataFrame(my_dictionary)

In [11]:
deneme1 = [1, 2, 3, 4, 5, "murat"]
my_dataFrame = pd.DataFrame(deneme1)
my_dataFrame

0
0      1
1      2
2      3
3      4
4      5
5  murat

In [12]:
deneme2 = ["murat", "havvanur", "eva"]
my_dataFrame2 = pd.DataFrame(deneme2, index=["index1", "index2", "index3"], columns=["kolon1"])
my_dataFrame2

kolon1
index1     murat
index2  havvanur
index3       eva

In [13]:
deneme3 = np.arange(1, 10).reshape(3,3)
my_dataFrame3 = pd.DataFrame(deneme3)
my_dataFrame3

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [14]:
my_dataFrame4 = pd.DataFrame(deneme3, 
                             index=["index1", 
                                    "index2",
                                    "index3"],
                             columns=["kolon1",
                                      "kolon2",
                                      "kolon3"])
my_dataFrame4

kolon1  kolon2  kolon3
index1       1       2       3
index2       4       5       6
index3       7       8       9

In [15]:
my_dataFrame4.columns

Index(['kolon1', 'kolon2', 'kolon3'], dtype='object')

In [16]:
my_dataFrame4.index

Index(['index1', 'index2', 'index3'], dtype='object')

In [17]:
my_dataFrame4.items

<bound method DataFrame.items of         kolon1  kolon2  kolon3
index1       1       2       3
index2       4       5       6
index3       7       8       9>

In [18]:
my_dataFrame4.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
my_dataFrame4.keys

<bound method NDFrame.keys of         kolon1  kolon2  kolon3
index1       1       2       3
index2       4       5       6
index3       7       8       9>

In [20]:
mydataset = {
    "cars":["BMW", "Volvo", "Ford"],
    "passings":[3, 5, 7]
}

my_dataFrame5 = pd.DataFrame(mydataset)
my_dataFrame5

cars  passings
0    BMW         3
1  Volvo         5
2   Ford         7

In [21]:
pd.__version__

'1.4.2'

In [22]:
deneme1 = pd.DataFrame(
    {
        "kolon1":{"index1":"deneme1",
                  "index2":"deneme2"}
    }
)

In [23]:
deneme1

kolon1
index1  deneme1
index2  deneme2

In [24]:
dictionary = {"index1":"murat",
              "index2":"havvanur",
              "index3":"eva"}
deneme2 = pd.DataFrame(
    {
        "kolon1": dictionary
    }
)

In [25]:
deneme2

kolon1
index1     murat
index2  havvanur
index3       eva

In [26]:
dictionary2 = {"index1":1,
               "index2":2,
               "index3":3,
               "index4":4}

column_dict = {"colon1": dictionary}

my_dataFrame6 = pd.DataFrame(column_dict)
my_dataFrame6

colon1
index1     murat
index2  havvanur
index3       eva

In [27]:
m = [1, 2, 3, 4, 5, 6, 7, 8]
df = pd.DataFrame(m, columns=["kolon1"] ,index=["index1", "index2", "index3", "index4", "index5", "index6", "index7", "index8"])
df

kolon1
index1       1
index2       2
index3       3
index4       4
index5       5
index6       6
index7       7
index8       8

In [28]:
k = np.arange(1, 17).reshape(4,4)
my_df = pd.DataFrame(k, columns=["kolon1", "kolon2", "kolon3", "kolon4"], index=["index1", "index2", "index3", "index4"])
my_df

kolon1  kolon2  kolon3  kolon4
index1       1       2       3       4
index2       5       6       7       8
index3       9      10      11      12
index4      13      14      15      16

In [29]:
my_df.head()

kolon1  kolon2  kolon3  kolon4
index1       1       2       3       4
index2       5       6       7       8
index3       9      10      11      12
index4      13      14      15      16

In [30]:
my_df.axes

[Index(['index1', 'index2', 'index3', 'index4'], dtype='object'),
 Index(['kolon1', 'kolon2', 'kolon3', 'kolon4'], dtype='object')]

In [31]:
my_df.shape

(4, 4)

In [32]:
my_df.size

16

In [33]:
type(my_df)

pandas.core.frame.DataFrame

In [34]:
my_df.ndim

2

In [35]:
my_df.keys

<bound method NDFrame.keys of         kolon1  kolon2  kolon3  kolon4
index1       1       2       3       4
index2       5       6       7       8
index3       9      10      11      12
index4      13      14      15      16>

In [36]:
my_df.values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [37]:
my_df.items

<bound method DataFrame.items of         kolon1  kolon2  kolon3  kolon4
index1       1       2       3       4
index2       5       6       7       8
index3       9      10      11      12
index4      13      14      15      16>

In [38]:
my_df.head()

kolon1  kolon2  kolon3  kolon4
index1       1       2       3       4
index2       5       6       7       8
index3       9      10      11      12
index4      13      14      15      16

In [39]:
my_df.head(1)

kolon1  kolon2  kolon3  kolon4
index1       1       2       3       4

In [40]:
my_df.head(2)

kolon1  kolon2  kolon3  kolon4
index1       1       2       3       4
index2       5       6       7       8

In [41]:
my_df.tail()

kolon1  kolon2  kolon3  kolon4
index1       1       2       3       4
index2       5       6       7       8
index3       9      10      11      12
index4      13      14      15      16

In [42]:
my_df.tail(1)

kolon1  kolon2  kolon3  kolon4
index4      13      14      15      16

In [43]:
my_df.tail(2)

kolon1  kolon2  kolon3  kolon4
index3       9      10      11      12
index4      13      14      15      16

In [49]:
#help(pd.DataFrame).head

In [50]:
#Parameters
# |  ----------
# |  data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
# |      Dict can contain Series, arrays, constants, dataclass or list-like objects. If
# |      data is a dict, column order follows insertion-order. If a dict contains Series
# |      which have an index defined, it is aligned by its index.
# |  
# |      .. versionchanged:: 0.25.0
# |         If data is a list of dicts, column order follows insertion-order.
# |  
# |  index : Index or array-like
# |      Index to use for resulting frame. Will default to RangeIndex if
# |      no indexing information part of input data and no index provided.
# |  columns : Index or array-like
# |      Column labels to use for resulting frame when data does not have them,
# |      defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
# |      will perform column selection instead.
# |  dtype : dtype, default None
# |      Data type to force. Only a single dtype is allowed. If None, infer.
# |  copy : bool or None, default None
# |      Copy data from inputs.
# |      For dict data, the default of None behaves like ``copy=True``.  For DataFrame
# |      or 2d ndarray input, the default of None behaves like ``copy=False``.
# |  
# |      .. versionchanged:: 1.3.0

In [55]:
sozluk1 = {"bmw":1, "mercedes":2}
sozluk2 = {"isim":"murat", "isim":"havvanur"}
sozluk3 = {"soyisim":"cengiz", "soyisim":"cengiz"}
print(sozluk1, sozluk2, sozluk3)

{'bmw': 1, 'mercedes': 2} {'isim': 'havvanur'} {'soyisim': 'cengiz'}


In [56]:
my_list = [sozluk1, sozluk2, sozluk3]
my_list

[{'bmw': 1, 'mercedes': 2}, {'isim': 'havvanur'}, {'soyisim': 'cengiz'}]

In [57]:
dataFrame = pd.DataFrame(my_list)

In [58]:
dataFrame

bmw  mercedes      isim soyisim
0  1.0       2.0       NaN     NaN
1  NaN       NaN  havvanur     NaN
2  NaN       NaN       NaN  cengiz

In [69]:
dataFrame.keys()

Index(['bmw', 'mercedes', 'isim', 'soyisim'], dtype='object')

In [71]:
dataFrame.values

array([[1.0, 2.0, nan, nan],
       [nan, nan, 'havvanur', nan],
       [nan, nan, nan, 'cengiz']], dtype=object)

In [72]:
dataFrame

bmw  mercedes      isim soyisim
0  1.0       2.0       NaN     NaN
1  NaN       NaN  havvanur     NaN
2  NaN       NaN       NaN  cengiz